title: My Github Learning Blog
author: Bob Downs
email: bobdowns@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Description of Github Learning Blog site.

# social links
twitter_username: @bobdownsinfo
github_username:  bobdownsnet

show_excerpts: true # set to false to remove excerpts on the homepage
